/**
 * API Analyzer - DataLeaf Component
 * * Purpose: Renders a single primitive leaf node from the normalized JSON Abstract Syntax Tree (AST).
 * * Constraints Enforced:
 * 1. Strict monospaced typography (JetBrains Mono/Courier) for structural JSON representation.
 * 2. Visual indention mapped dynamically to the AST recursion depth.
 * 3. Incorporates metadata badges (Type Inference & PII Warnings) aligned to the right margin.
 * * Dependencies: Consumes `NormalizedNode` from the AST pipeline and delegates 
 * threat rendering to the `PiiRedBadge` component.
 */

import React from 'react';
import { cn } from '../../utils/cn';
import type { NormalizedNode } from '../../core/astNormalizer';
import { PiiRedBadge } from '../metrics/PiiRedBadge';

export interface DataLeafProps extends React.HTMLAttributes<HTMLDivElement> {
    /** The fully processed primitive AST node to render. */
    node: NormalizedNode;
}

/**
 * Instantiates the DataLeaf with standard React ref forwarding.
 * @param props - Component-specific properties merged with standard HTML div attributes.
 */
export const DataLeaf = React.forwardRef<HTMLDivElement, DataLeafProps>(
    ({ className, node, ...props }, ref) => {
        // Calculate structural indentation utilizing rem units for responsive scaling
        const indentStyle = { paddingLeft: `${node.depth * 1.25}rem` };

        // Primitive Serialization Logic
        let displayValue = 'null';
        let isNull = false;

        if (node.value === null) {
            isNull = true;
        } else if (typeof node.value === 'boolean') {
            displayValue = node.value ? 'true' : 'false';
        } else if (typeof node.value === 'string') {
            displayValue = node.value === '' ? '""' : node.value;
        } else if (typeof node.value === 'number') {
            // Prioritize mathematically truncated float bins if generated by the pipeline
            displayValue = node.binnedValue !== undefined ? node.binnedValue : String(node.value);
        }

        return (
            <div 
                ref={ref}
                className={cn(
                    "flex flex-col sm:flex-row sm:items-start py-1.5 border-b border-gray-100 hover:bg-gray-50 transition-colors font-mono text-xs sm:text-sm",
                    className
                )}
                style={indentStyle}
                {...props}
            >
                {/* Node Key / Array Index */}
                <div className="flex-shrink-0 sm:w-48 pr-4 mb-1 sm:mb-0">
                    <span className="font-bold text-black selection:bg-black selection:text-white">
                        {typeof node.key === 'string' ? node.key : `[${node.key}]`}
                    </span>
                    <span className="text-gray-400 ml-1">:</span>
                </div>

                {/* Node Primitive Value & Metadata Block */}
                <div className="flex-grow flex flex-col sm:flex-row sm:items-start justify-between gap-2 break-all">
                    
                    {/* Value Container */}
                    <span className={cn(
                        "text-black selection:bg-black selection:text-white",
                        isNull && "text-gray-400 italic",
                        typeof node.value === 'string' && "text-gray-900",
                        typeof node.value === 'number' && "font-bold tracking-tight",
                        typeof node.value === 'boolean' && "font-bold uppercase text-[10px] sm:text-xs"
                    )}>
                        {displayValue}
                    </span>

                    {/* Metadata Indicators (Type & PII) */}
                    <div className="flex items-center gap-2 mt-1 sm:mt-0 flex-shrink-0">
                        <span 
                            className="inline-block border border-gray-300 text-gray-500 px-1.5 py-0.5 text-[9px] uppercase tracking-widest bg-white"
                            title={`Inferred Semantic Type: ${node.type}`}
                        >
                            {node.type}
                        </span>
                        <PiiRedBadge level={node.pii.threatLevel} typeLabel={node.pii.type} />
                    </div>
                </div>
            </div>
        );
    }
);

DataLeaf.displayName = 'DataLeaf';