/**
 * API Analyzer - EditorialGrid Component
 * * Purpose: The master container for rendering the fully normalized JSON Abstract Syntax Tree (AST).
 * * Structural Constraints:
 * 1. Establishes the outermost "Newsprint" bounding box and overarching metric summary header.
 * 2. Dynamically orchestrates the rendering of structural AST nodes (ObjectColumn/ArrayList) vs 
 * primitive fallback arrays (though the root is almost exclusively an Object or Array).
 * * Dependencies: Consumes `NormalizedNode` and `PayloadMetrics`.
 */

import React, { useMemo } from 'react';
import { cn } from '../../utils/cn';
import type { NormalizedNode } from '../../core/astNormalizer';
import type { PayloadMetrics } from '../../core/metricCalculator';
import { ObjectColumn } from './ObjectColumn';
import { ArrayList } from './ArrayList';
import { DataLeaf } from './DataLeaf';

export interface EditorialGridProps extends React.HTMLAttributes<HTMLDivElement> {
    /** The fully processed root AST node representing the entire API response. */
    dataNode: NormalizedNode;
    /** Calculated ingestion metrics for the header display. */
    metrics: PayloadMetrics;
    /** Active KV filters mapped from the UniqueKeyFilter module. */
    activeFilters?: Record<string, string>;
}

/**
 * Normalizes an AST primitive leaf value to perfectly match the stringified 
 * format generated by the metricCalculator's tracking logic.
 */
const stringifyLeafValue = (val: string | number | boolean | null): string => {
    if (val === null) return 'null';
    if (typeof val === 'boolean') return val ? 'true' : 'false';
    if (typeof val === 'string') return `"${val}"`;
    // For float comparison without importing floatBinner, cast to string. 
    // Exact match is required.
    return String(val); 
};

/**
 * Recursively traverses and prunes the AST based on active filters.
 * Execution Rule: If a node is an Object, and contains a key matching a filter,
 * but its value does NOT match the filter's selected value, drop the entire Object.
 */
const filterAst = (node: NormalizedNode, filters: Record<string, string>): NormalizedNode | null => {
    if (!filters || Object.keys(filters).length === 0) return node;

    if (node.isExpandable && node.children) {
        // Evaluate Object nodes against active filter constraints
        if (node.type.startsWith('Object')) {
            for (const [filterKey, filterValue] of Object.entries(filters)) {
                const matchedChild = node.children.find(c => String(c.key) === filterKey);
                
                // If the object possesses the filtered key, enforce the value constraint
                if (matchedChild) {
                    const childValueStr = stringifyLeafValue(matchedChild.value);
                    if (childValueStr !== filterValue) {
                        return null; // Prune entire branch from tree
                    }
                }
            }
        }

        // Recursively filter surviving children
        const filteredChildren = node.children
            .map(child => filterAst(child, filters))
            .filter((child): child is NormalizedNode => child !== null);

        // Return cloned immutable node with filtered children
        return { ...node, children: filteredChildren };
    }

    return node;
};

export const EditorialGrid = React.forwardRef<HTMLDivElement, EditorialGridProps>(
    ({ className, dataNode, metrics, activeFilters = {}, ...props }, ref) => {
        
        // Execute structural pruning whenever filters or payload mutates
        const renderedAst = useMemo(() => {
            return filterAst(dataNode, activeFilters);
        }, [dataNode, activeFilters]);

        const formatSize = (bytes: number) => {
            return (bytes / 1024).toFixed(2) + ' KB';
        };

        return (
            <div 
                ref={ref}
                className={cn(
                    "flex flex-col border-[4px] border-black bg-white",
                    className
                )}
                {...props}
            >
                {/* Master Grid Header: Metrics & Telemetry Summary */}
                <div className="bg-black text-white p-4 border-b-[4px] border-black flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
                    <div>
                        <h2 className="font-serif text-2xl font-bold uppercase tracking-widest text-white selection:bg-white selection:text-black">
                            AST Telemetry Log
                        </h2>
                        <p className="font-mono text-xs mt-1 text-gray-300">
                            {Object.keys(activeFilters).length > 0 
                                ? `STRUCTURAL ANALYSIS FILTERED (${Object.keys(activeFilters).length} ACTIVE)` 
                                : 'STRUCTURAL ANALYSIS COMPLETE'}
                        </p>
                    </div>
                    
                    <div className="flex flex-wrap gap-4 font-mono text-xs sm:text-sm font-bold uppercase tracking-widest">
                        <div className="flex flex-col bg-white text-black px-3 py-1 text-center">
                            <span className="text-[9px] text-gray-500">MAX DEPTH</span>
                            <span>{metrics.maxDepth}</span>
                        </div>
                        <div className="flex flex-col bg-white text-black px-3 py-1 text-center">
                            <span className="text-[9px] text-gray-500">PAYLOAD WT.</span>
                            <span>{formatSize(metrics.totalByteSize)}</span>
                        </div>
                    </div>
                </div>

                {/* Recursive AST Render Boundary */}
                <div className="p-4 sm:p-6 overflow-x-auto min-h-[200px]">
                    {!renderedAst ? (
                        <div className="flex items-center justify-center h-full text-gray-400 font-mono text-sm uppercase tracking-widest p-8 border border-dashed border-gray-300">
                            [ ZERO NODES MATCH FILTER CRITERIA ]
                        </div>
                    ) : (
                        <>
                            {renderedAst.type.startsWith('Object') && (
                                <ObjectColumn node={renderedAst} className="border-none" />
                            )}
                            
                            {renderedAst.type.startsWith('Array') && (
                                <ArrayList node={renderedAst} className="border-none" />
                            )}
                            
                            {!renderedAst.type.startsWith('Object') && !renderedAst.type.startsWith('Array') && (
                                <div className="border border-black p-2 bg-gray-50/50">
                                    <DataLeaf node={renderedAst} className="border-none" />
                                </div>
                            )}
                        </>
                    )}
                </div>
            </div>
        );
    }
);

EditorialGrid.displayName = 'EditorialGrid';